### PR TITLE
added support for $ne operator

### PR DESCRIPTION
**Pull request by roxanne-mackinnon**
## Describe your changes
Added support for $ne comparison operator in query/filter, to test not-equal
## How best to test these changes
Added tests to query/filter/comparison_test.go
## Issue ticket number and link
/claim #873 for algora bounty

### CODE REVIEW

**Comment by himank** [comment]
Overall, it is the right direction. But change it like this,
- `$ne` will implement `LikeMatcher` interface
-  Then this matcher will be used by `LikeFilter,` which you'll add in the second case in `filter.go` at line 359.
The reason for doing it this way is that we don't want to implement keys from this filter and mainly only want to use it for filtering.

Once this is done, please add a test in `test/v1/server/document_test.go` where we have other Read API integration tests.

**Comment by roxanne-mackinnon** [comment]
> Overall, it is the right direction. But change it like this,
> 
>     * `$ne` will implement `LikeMatcher` interface
> 
>     * Then this matcher will be used by `LikeFilter,` which you'll add in the second case in `filter.go` at line 359.
>       The reason for doing it this way is that we don't want to implement keys from this filter and mainly only want to use it for filtering.
> 
> 
> Once this is done, please add a test in `test/v1/server/document_test.go` where we have other Read API integration tests.

If I'm understanding correctly, do you mean that `$ne` should only implement LikeMatcher, or should it also implement ValueMatcher? Also, is the purpose of `$ne` to do exact string comparison, as opposed to `$not` which is more like 'does not contain'?

**Comment by himank** [comment]
> > Overall, it is the right direction. But change it like this,
> 
> > 
> 
> >     * `$ne` will implement `LikeMatcher` interface
> 
> > 
> 
> >     * Then this matcher will be used by `LikeFilter,` which you'll add in the second case in `filter.go` at line 359.
> 
> >       The reason for doing it this way is that we don't want to implement keys from this filter and mainly only want to use it for filtering.
> 
> > 
> 
> > 
> 
> > Once this is done, please add a test in `test/v1/server/document_test.go` where we have other Read API integration tests.
> 
> 
> 
> If I'm understanding correctly, do you mean that `$ne` should only implement LikeMatcher, or should it also implement ValueMatcher? Also, is the purpose of `$ne` to do exact string comparison, as opposed to `$not` which is more like 'does not contain'?

That's right only LikeMatcher. Correct $ne is for exact not equality comparison.

**Comment by himank** [comment]
Looks good, can you rebase it, and I'll merge it.

**Pull request closed without merging**
