### PR TITLE
feat: Namespace API list/info/describe consolidation. 

### PR DESCRIPTION
**Pull request by JigarJoshi**
## Describe your changes
Implemented a management API to get the namespace information and consolidated list/info/describe into single API.

## How best to test these changes
Added tests for it.

### CODE REVIEW

**Comment by efirs** [comment]
Would it be easier to add a filter to list namespaces API?

**Comment by JigarJoshi** [comment]
> Would it be easier to add a filter to list namespaces API?

Yes but namespaceinfo api can extend to serve other information that we may need.

**Comment by efirs** [comment]
ok. It just we have get/list/describe and it a bit inconsistent with other APIs.

**Comment by ovaistariq** [comment]
Should we extend list namespaces to return additional information when an option is passed?

**Comment by ovaistariq** [comment]
Or may be make the namespace info part of the describe endpoint.

**Comment by JigarJoshi** [comment]
we internally had discussion and decided to consolidate describe/info/list into single RPC method.

**Review by himank — APPROVED** [review]

**Pull request merged**
